export const queryResponse = {
  parent_id: '61eebd1b9e5052d210b5ecfdfff7f055',
  sql_changed: true,
  aggregate_table_used_info: null,
  added_params: null,
  data: [
    {
      'users.gender': {
        value: 'Male',
      },
      'order_items.average_sale_price': {
        value: 47.92918670638953,
        rendered: '$47.93',
        links: [
          {
            label: 'Show All $47.93',
            label_prefix: 'Show All',
            label_value: '$47.93',
            url: '/explore/thelook_partner/order_items?fields=order_items.order_id,order_items.status,order_items.created_date,order_items.sale_price,products.brand,products.item_name,users.name,users.email&f[users.gender]=Male&f[users.state]=&f[users.city]=&f[users.traffic_source]=&f[order_items.created_date]=90+days&f[distribution_centers.location]=&f[users.country]=&query_timezone=Europe%2FMadrid&limit=500',
            type: 'measure_default',
          },
        ],
      },
      'order_items.count': {
        value: 13768,
        rendered: '13,768',
        links: [
          {
            label: 'Show All 13,768',
            label_prefix: 'Show All',
            label_value: '13,768',
            url: '/explore/thelook_partner/order_items?fields=order_items.order_id,order_items.status,order_items.created_date,order_items.sale_price,products.brand,products.item_name,users.name,users.email&f[users.gender]=Male&f[users.state]=&f[users.city]=&f[users.traffic_source]=&f[order_items.created_date]=90+days&f[distribution_centers.location]=&f[users.country]=&query_timezone=Europe%2FMadrid&limit=500',
            type: 'measure_default',
          },
        ],
      },
      'order_items.total_sale_price': {
        value: 659889.0425735712,
        rendered: '$659,889.04',
        links: [
          {
            label: 'Show All $659,889.04',
            label_prefix: 'Show All',
            label_value: '$659,889.04',
            url: '/explore/thelook_partner/order_items?fields=order_items.total_sale_price,products.category&f[users.gender]=Male&f[users.state]=&f[users.city]=&f[users.traffic_source]=&f[order_items.created_date]=90+days&f[distribution_centers.location]=&f[users.country]=&query_timezone=Europe%2FMadrid&limit=500',
            type: 'measure_default',
          },
        ],
      },
    },
    {
      'users.gender': {
        value: 'Female',
      },
      'order_items.average_sale_price': {
        value: 44.27421166761676,
        rendered: '$44.27',
        links: [
          {
            label: 'Show All $44.27',
            label_prefix: 'Show All',
            label_value: '$44.27',
            url: '/explore/thelook_partner/order_items?fields=order_items.order_id,order_items.status,order_items.created_date,order_items.sale_price,products.brand,products.item_name,users.name,users.email&f[users.gender]=Female&f[users.state]=&f[users.city]=&f[users.traffic_source]=&f[order_items.created_date]=90+days&f[distribution_centers.location]=&f[users.country]=&query_timezone=Europe%2FMadrid&limit=500',
            type: 'measure_default',
          },
        ],
      },
      'order_items.count': {
        value: 17343,
        rendered: '17,343',
        links: [
          {
            label: 'Show All 17,343',
            label_prefix: 'Show All',
            label_value: '17,343',
            url: '/explore/thelook_partner/order_items?fields=order_items.order_id,order_items.status,order_items.created_date,order_items.sale_price,products.brand,products.item_name,users.name,users.email&f[users.gender]=Female&f[users.state]=&f[users.city]=&f[users.traffic_source]=&f[order_items.created_date]=90+days&f[distribution_centers.location]=&f[users.country]=&query_timezone=Europe%2FMadrid&limit=500',
            type: 'measure_default',
          },
        ],
      },
      'order_items.total_sale_price': {
        value: 767847.652951479,
        rendered: '$767,847.65',
        links: [
          {
            label: 'Show All $767,847.65',
            label_prefix: 'Show All',
            label_value: '$767,847.65',
            url: '/explore/thelook_partner/order_items?fields=order_items.total_sale_price,products.category&f[users.gender]=Female&f[users.state]=&f[users.city]=&f[users.traffic_source]=&f[order_items.created_date]=90+days&f[distribution_centers.location]=&f[users.country]=&query_timezone=Europe%2FMadrid&limit=500',
            type: 'measure_default',
          },
        ],
      },
    },
  ],
  drill_menu_build_time: 0.042523000000000005,
  drill_metadata: {
    field_map: {},
    template:
      '/explore/thelook_partner/order_items?fields=order_items.average_sale_price,users.gender,order_items.count,order_items.total_sale_price,<DRILL_BY>&f[users.state]=&f[users.city]=&f[users.traffic_source]=&f[users.gender]=&f[order_items.created_date]=90+days&f[distribution_centers.location]=&f[users.country]=&sorts=orders.average_profit desc,order_items.average_sale_price desc&limit=500&column_limit=50&total=true&dynamic_fields=%5B%7B%22table_calculation%22%3A%22date%22%2C%22label%22%3A%22date%22%2C%22expression%22%3A%22now%28%29%22%2C%22value_format%22%3Anull%2C%22value_format_name%22%3Anull%2C%22_kind_hint%22%3A%22dimension%22%2C%22is_disabled%22%3Atrue%7D%5D&query_timezone=user_timezone&f[<DRILL_INTO>]=<DRILL_VALUE>',
  },
  expired: false,
  fields: {
    measures: [
      {
        align: 'right',
        can_filter: true,
        category: 'measure',
        default_filter_value: null,
        description: 'Average of Items Sale Price',
        enumerations: null,
        field_group_label: null,
        fill_style: null,
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: true,
        label: 'Order Items Average Sale Price',
        label_from_parameter: null,
        label_short: 'Average Sale Price',
        map_layer: null,
        name: 'order_items.average_sale_price',
        strict_value_format: false,
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: ['Average of Items Sale Price'],
        type: 'average',
        user_attribute_filter_types: ['number', 'advanced_filter_number'],
        value_format: '$#,##0.00',
        view: 'order_items',
        view_label: 'Order Items',
        dynamic: false,
        week_start_day: 'monday',
        original_view: 'order_items',
        dimension_group: null,
        error: null,
        field_group_variant: 'Average Sale Price',
        measure: true,
        parameter: false,
        primary_key: false,
        project_name: 'looker_partner_demo',
        scope: 'order_items',
        suggest_dimension: 'order_items.average_sale_price',
        suggest_explore: 'order_items',
        suggestable: false,
        is_fiscal: false,
        is_timeframe: false,
        can_time_filter: false,
        time_interval: null,
        lookml_link:
          '/projects/looker_partner_demo/files/views%2F01_order_items.view.lkml?line=356',
        permanent: null,
        source_file: 'views/01_order_items.view.lkml',
        source_file_path: 'looker_partner_demo/views/01_order_items.view.lkml',
        sql: '${sale_price} ',
        sql_case: null,
        filters: null,
        times_used: 0,
        sorted: {
          desc: true,
          sort_index: 1,
        },
      },
      {
        align: 'right',
        can_filter: true,
        category: 'measure',
        default_filter_value: null,
        description: '',
        enumerations: null,
        field_group_label: null,
        fill_style: null,
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: true,
        label: 'Order Items Count',
        label_from_parameter: null,
        label_short: 'Count',
        map_layer: null,
        name: 'order_items.count',
        strict_value_format: false,
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: [],
        type: 'count',
        user_attribute_filter_types: ['number', 'advanced_filter_number'],
        value_format: null,
        view: 'order_items',
        view_label: 'Order Items',
        dynamic: false,
        week_start_day: 'monday',
        original_view: 'order_items',
        dimension_group: null,
        error: null,
        field_group_variant: 'Count',
        measure: true,
        parameter: false,
        primary_key: false,
        project_name: 'looker_partner_demo',
        scope: 'order_items',
        suggest_dimension: 'order_items.count',
        suggest_explore: 'order_items',
        suggestable: false,
        is_fiscal: false,
        is_timeframe: false,
        can_time_filter: false,
        time_interval: null,
        lookml_link:
          '/projects/looker_partner_demo/files/views%2F01_order_items.view.lkml?line=57',
        permanent: null,
        source_file: 'views/01_order_items.view.lkml',
        source_file_path: 'looker_partner_demo/views/01_order_items.view.lkml',
        sql: null,
        sql_case: null,
        filters: null,
        times_used: 0,
      },
      {
        align: 'right',
        can_filter: true,
        category: 'measure',
        default_filter_value: null,
        description: '',
        enumerations: null,
        field_group_label: null,
        fill_style: null,
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: true,
        label: 'Order Items Total Sale Price',
        label_from_parameter: null,
        label_short: 'Total Sale Price',
        map_layer: null,
        name: 'order_items.total_sale_price',
        strict_value_format: false,
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: [],
        type: 'sum',
        user_attribute_filter_types: ['number', 'advanced_filter_number'],
        value_format: '$#,##0.00',
        view: 'order_items',
        view_label: 'Order Items',
        dynamic: false,
        week_start_day: 'monday',
        original_view: 'order_items',
        dimension_group: null,
        error: null,
        field_group_variant: 'Total Sale Price',
        measure: true,
        parameter: false,
        primary_key: false,
        project_name: 'looker_partner_demo',
        scope: 'order_items',
        suggest_dimension: 'order_items.total_sale_price',
        suggest_explore: 'order_items',
        suggestable: false,
        is_fiscal: false,
        is_timeframe: false,
        can_time_filter: false,
        time_interval: null,
        lookml_link:
          '/projects/looker_partner_demo/files/views%2F01_order_items.view.lkml?line=338',
        permanent: null,
        source_file: 'views/01_order_items.view.lkml',
        source_file_path: 'looker_partner_demo/views/01_order_items.view.lkml',
        sql: '${sale_price} ',
        sql_case: null,
        filters: null,
        times_used: 0,
      },
    ],
    dimensions: [
      {
        align: 'left',
        can_filter: true,
        category: 'dimension',
        default_filter_value: null,
        description: 'Users/Customers gender',
        enumerations: null,
        field_group_label: null,
        fill_style: null,
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: false,
        label: 'Users Gender',
        label_from_parameter: null,
        label_short: 'Gender',
        map_layer: null,
        name: 'users.gender',
        strict_value_format: false,
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: ['Users/Customers gender'],
        type: 'string',
        user_attribute_filter_types: ['string', 'advanced_filter_string'],
        value_format: null,
        view: 'users',
        view_label: 'Users',
        dynamic: false,
        week_start_day: 'monday',
        original_view: 'users',
        dimension_group: null,
        error: null,
        field_group_variant: 'Gender',
        measure: false,
        parameter: false,
        primary_key: false,
        project_name: 'looker_partner_demo',
        scope: 'users',
        suggest_dimension: 'users.gender',
        suggest_explore: 'order_items',
        suggestable: true,
        is_fiscal: false,
        is_timeframe: false,
        can_time_filter: false,
        time_interval: null,
        lookml_link:
          '/projects/looker_partner_demo/files/views%2F02_users.view.lkml?line=82',
        permanent: null,
        source_file: 'views/02_users.view.lkml',
        source_file_path: 'looker_partner_demo/views/02_users.view.lkml',
        sql: '${TABLE}.gender ',
        sql_case: null,
        filters: null,
        times_used: 0,
      },
    ],
    table_calculations: [],
    pivots: [],
    measure_like: [
      {
        align: 'right',
        can_filter: true,
        category: 'measure',
        default_filter_value: null,
        description: 'Average of Items Sale Price',
        enumerations: null,
        field_group_label: null,
        fill_style: null,
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: true,
        label: 'Order Items Average Sale Price',
        label_from_parameter: null,
        label_short: 'Average Sale Price',
        map_layer: null,
        name: 'order_items.average_sale_price',
        strict_value_format: false,
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: ['Average of Items Sale Price'],
        type: 'average',
        user_attribute_filter_types: ['number', 'advanced_filter_number'],
        value_format: '$#,##0.00',
        view: 'order_items',
        view_label: 'Order Items',
        dynamic: false,
        week_start_day: 'monday',
        original_view: 'order_items',
        dimension_group: null,
        error: null,
        field_group_variant: 'Average Sale Price',
        measure: true,
        parameter: false,
        primary_key: false,
        project_name: 'looker_partner_demo',
        scope: 'order_items',
        suggest_dimension: 'order_items.average_sale_price',
        suggest_explore: 'order_items',
        suggestable: false,
        is_fiscal: false,
        is_timeframe: false,
        can_time_filter: false,
        time_interval: null,
        lookml_link:
          '/projects/looker_partner_demo/files/views%2F01_order_items.view.lkml?line=356',
        permanent: null,
        source_file: 'views/01_order_items.view.lkml',
        source_file_path: 'looker_partner_demo/views/01_order_items.view.lkml',
        sql: '${sale_price} ',
        sql_case: null,
        filters: null,
        times_used: 0,
        sorted: {
          desc: true,
          sort_index: 1,
        },
      },
      {
        align: 'right',
        can_filter: true,
        category: 'measure',
        default_filter_value: null,
        description: '',
        enumerations: null,
        field_group_label: null,
        fill_style: null,
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: true,
        label: 'Order Items Count',
        label_from_parameter: null,
        label_short: 'Count',
        map_layer: null,
        name: 'order_items.count',
        strict_value_format: false,
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: [],
        type: 'count',
        user_attribute_filter_types: ['number', 'advanced_filter_number'],
        value_format: null,
        view: 'order_items',
        view_label: 'Order Items',
        dynamic: false,
        week_start_day: 'monday',
        original_view: 'order_items',
        dimension_group: null,
        error: null,
        field_group_variant: 'Count',
        measure: true,
        parameter: false,
        primary_key: false,
        project_name: 'looker_partner_demo',
        scope: 'order_items',
        suggest_dimension: 'order_items.count',
        suggest_explore: 'order_items',
        suggestable: false,
        is_fiscal: false,
        is_timeframe: false,
        can_time_filter: false,
        time_interval: null,
        lookml_link:
          '/projects/looker_partner_demo/files/views%2F01_order_items.view.lkml?line=57',
        permanent: null,
        source_file: 'views/01_order_items.view.lkml',
        source_file_path: 'looker_partner_demo/views/01_order_items.view.lkml',
        sql: null,
        sql_case: null,
        filters: null,
        times_used: 0,
      },
      {
        align: 'right',
        can_filter: true,
        category: 'measure',
        default_filter_value: null,
        description: '',
        enumerations: null,
        field_group_label: null,
        fill_style: null,
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: true,
        label: 'Order Items Total Sale Price',
        label_from_parameter: null,
        label_short: 'Total Sale Price',
        map_layer: null,
        name: 'order_items.total_sale_price',
        strict_value_format: false,
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: [],
        type: 'sum',
        user_attribute_filter_types: ['number', 'advanced_filter_number'],
        value_format: '$#,##0.00',
        view: 'order_items',
        view_label: 'Order Items',
        dynamic: false,
        week_start_day: 'monday',
        original_view: 'order_items',
        dimension_group: null,
        error: null,
        field_group_variant: 'Total Sale Price',
        measure: true,
        parameter: false,
        primary_key: false,
        project_name: 'looker_partner_demo',
        scope: 'order_items',
        suggest_dimension: 'order_items.total_sale_price',
        suggest_explore: 'order_items',
        suggestable: false,
        is_fiscal: false,
        is_timeframe: false,
        can_time_filter: false,
        time_interval: null,
        lookml_link:
          '/projects/looker_partner_demo/files/views%2F01_order_items.view.lkml?line=338',
        permanent: null,
        source_file: 'views/01_order_items.view.lkml',
        source_file_path: 'looker_partner_demo/views/01_order_items.view.lkml',
        sql: '${sale_price} ',
        sql_case: null,
        filters: null,
        times_used: 0,
      },
    ],
    dimension_like: [
      {
        align: 'left',
        can_filter: true,
        category: 'dimension',
        default_filter_value: null,
        description: 'Users/Customers gender',
        enumerations: null,
        field_group_label: null,
        fill_style: null,
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: false,
        label: 'Users Gender',
        label_from_parameter: null,
        label_short: 'Gender',
        map_layer: null,
        name: 'users.gender',
        strict_value_format: false,
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: ['Users/Customers gender'],
        type: 'string',
        user_attribute_filter_types: ['string', 'advanced_filter_string'],
        value_format: null,
        view: 'users',
        view_label: 'Users',
        dynamic: false,
        week_start_day: 'monday',
        original_view: 'users',
        dimension_group: null,
        error: null,
        field_group_variant: 'Gender',
        measure: false,
        parameter: false,
        primary_key: false,
        project_name: 'looker_partner_demo',
        scope: 'users',
        suggest_dimension: 'users.gender',
        suggest_explore: 'order_items',
        suggestable: true,
        is_fiscal: false,
        is_timeframe: false,
        can_time_filter: false,
        time_interval: null,
        lookml_link:
          '/projects/looker_partner_demo/files/views%2F02_users.view.lkml?line=82',
        permanent: null,
        source_file: 'views/02_users.view.lkml',
        source_file_path: 'looker_partner_demo/views/02_users.view.lkml',
        sql: '${TABLE}.gender ',
        sql_case: null,
        filters: null,
        times_used: 0,
      },
    ],
  },
  fill_fields: [],
  forecast_result: null,
  has_row_totals: false,
  has_totals: true,
  id: 'query-result-7:{"hidden_points_if_no":[],"hidden_fields":[]}',
  null_sort_treatment: 'low',
  number_format: '1,234.56',
  ran_at: '2024-10-24T07:48:42Z',
  runtime: '1.856',
  server_id: '38651',
  sql: "SELECT\n    users.gender  AS users_gender,\n    AVG(order_items.sale_price ) AS order_items_average_sale_price,\n    COUNT(*) AS order_items_count,\n    COALESCE(SUM(order_items.sale_price ), 0) AS order_items_total_sale_price\nFROM looker-private-demo.ecomm.order_items  AS order_items\nLEFT JOIN looker-private-demo.ecomm.users  AS users ON order_items.user_id = users.id\nWHERE ((( order_items.created_at  ) >= ((TIMESTAMP(DATETIME_ADD(DATETIME(TIMESTAMP_TRUNC(CURRENT_TIMESTAMP(), DAY, 'Europe/Madrid'), 'Europe/Madrid'), INTERVAL -89 DAY), 'Europe/Madrid'))) AND ( order_items.created_at  ) < ((TIMESTAMP(DATETIME_ADD(DATETIME(TIMESTAMP(DATETIME_ADD(DATETIME(TIMESTAMP_TRUNC(CURRENT_TIMESTAMP(), DAY, 'Europe/Madrid'), 'Europe/Madrid'), INTERVAL -89 DAY), 'Europe/Madrid'), 'Europe/Madrid'), INTERVAL 90 DAY), 'Europe/Madrid')))))\nGROUP BY\n    1\nORDER BY\n    2 DESC\nLIMIT 500\n\n-- sql for creating the total and/or determining pivot columns\nSELECT\n    AVG(order_items.sale_price ) AS order_items_average_sale_price,\n    COUNT(*) AS order_items_count,\n    COALESCE(SUM(order_items.sale_price ), 0) AS order_items_total_sale_price\nFROM looker-private-demo.ecomm.order_items  AS order_items\nLEFT JOIN looker-private-demo.ecomm.users  AS users ON order_items.user_id = users.id\nWHERE ((( order_items.created_at  ) >= ((TIMESTAMP(DATETIME_ADD(DATETIME(TIMESTAMP_TRUNC(CURRENT_TIMESTAMP(), DAY, 'Europe/Madrid'), 'Europe/Madrid'), INTERVAL -89 DAY), 'Europe/Madrid'))) AND ( order_items.created_at  ) < ((TIMESTAMP(DATETIME_ADD(DATETIME(TIMESTAMP(DATETIME_ADD(DATETIME(TIMESTAMP_TRUNC(CURRENT_TIMESTAMP(), DAY, 'Europe/Madrid'), 'Europe/Madrid'), INTERVAL -89 DAY), 'Europe/Madrid'), 'Europe/Madrid'), INTERVAL 90 DAY), 'Europe/Madrid')))))\nLIMIT 1",
  sql_explain: null,
  supports_pivot_in_db: true,
  timezone: 'Europe/Madrid',
  totals_data: {
    'order_items.average_sale_price': {
      value: 45.89170054080723,
      has_custom_html: false,
      html: "<a href='/explore/thelook_partner/order_items?fields=order_items.order_id,order_items.status,order_items.created_date,order_items.sale_price,products.brand,products.item_name,users.name,users.email&f[users.state]=&f[users.city]=&f[users.traffic_source]=&f[order_items.created_date]=90+days&f[distribution_centers.location]=&f[users.country]=&query_timezone=Europe%2FMadrid&limit=500' class='cell-clickable-content' target='_self'>$45.89</a>",
      links: [
        {
          url: '/explore/thelook_partner/order_items?fields=order_items.order_id,order_items.status,order_items.created_date,order_items.sale_price,products.brand,products.item_name,users.name,users.email&f[users.state]=&f[users.city]=&f[users.traffic_source]=&f[order_items.created_date]=90+days&f[distribution_centers.location]=&f[users.country]=&query_timezone=Europe%2FMadrid&limit=500',
        },
      ],
    },
    'order_items.count': {
      value: 31111,
      has_custom_html: false,
      html: "<a href='/explore/thelook_partner/order_items?fields=order_items.order_id,order_items.status,order_items.created_date,order_items.sale_price,products.brand,products.item_name,users.name,users.email&f[users.state]=&f[users.city]=&f[users.traffic_source]=&f[order_items.created_date]=90+days&f[distribution_centers.location]=&f[users.country]=&query_timezone=Europe%2FMadrid&limit=500' class='cell-clickable-content' target='_self'>31,111</a>",
      links: [
        {
          url: '/explore/thelook_partner/order_items?fields=order_items.order_id,order_items.status,order_items.created_date,order_items.sale_price,products.brand,products.item_name,users.name,users.email&f[users.state]=&f[users.city]=&f[users.traffic_source]=&f[order_items.created_date]=90+days&f[distribution_centers.location]=&f[users.country]=&query_timezone=Europe%2FMadrid&limit=500',
        },
      ],
    },
    'order_items.total_sale_price': {
      value: 1427736.6955250502,
      has_custom_html: false,
      html: "<a href='/explore/thelook_partner/order_items?fields=order_items.total_sale_price,products.category&f[users.state]=&f[users.city]=&f[users.traffic_source]=&f[order_items.created_date]=90+days&f[distribution_centers.location]=&f[users.country]=&query_timezone=Europe%2FMadrid&limit=500' class='cell-clickable-content' target='_self'>$1,427,736.70</a>",
      links: [
        {
          url: '/explore/thelook_partner/order_items?fields=order_items.total_sale_price,products.category&f[users.state]=&f[users.city]=&f[users.traffic_source]=&f[order_items.created_date]=90+days&f[distribution_centers.location]=&f[users.country]=&query_timezone=Europe%2FMadrid&limit=500',
        },
      ],
    },
  },
  is_local: true,
  table_calcs_complete: true,
  tracked_attributes: {
    'result.drill_menu_build_time': 0.042523000000000005,
    'result.from_cache': false,
    'result.runtime': '1.856',
    'result.sql.length': 1739,
    'result.supports_pivot_in_db': true,
  },
  sorts: [],
};

export const config = {
  font_size_main: '',
  orientation: 'auto',
  'style_users.gender': '#3A4245',
  'show_title_users.gender': true,
  'title_placement_users.gender': 'above',
  'value_format_users.gender': '',
  customTheme: '',
  loadCustomTheme: false,
  'style_order_items.average_sale_price': '#3A4245',
  'show_title_order_items.average_sale_price': true,
  'title_placement_order_items.average_sale_price': 'above',
  'value_format_order_items.average_sale_price': '',
  'show_comparison_order_items.average_sale_price': false,
  'style_order_items.count': '#3A4245',
  'show_title_order_items.count': true,
  'title_placement_order_items.count': 'above',
  'value_format_order_items.count': '',
  'show_comparison_order_items.count': false,
  'style_order_items.total_sale_price': '#3A4245',
  'show_title_order_items.total_sale_price': true,
  'title_placement_order_items.total_sale_price': 'above',
  'value_format_order_items.total_sale_price': '',
  'show_comparison_order_items.total_sale_price': false,
  type: 'multiple-tile::multiple-id-private',
  query_fields: {
    measures: [
      {
        align: 'right',
        can_filter: true,
        category: 'measure',
        default_filter_value: null,
        description: 'Average of Items Sale Price',
        enumerations: null,
        field_group_label: null,
        fill_style: null,
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: true,
        label: 'Order Items Average Sale Price',
        label_from_parameter: null,
        label_short: 'Average Sale Price',
        map_layer: null,
        name: 'order_items.average_sale_price',
        strict_value_format: false,
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: ['Average of Items Sale Price'],
        type: 'average',
        user_attribute_filter_types: ['number', 'advanced_filter_number'],
        value_format: '$#,##0.00',
        view: 'order_items',
        view_label: 'Order Items',
        dynamic: false,
        week_start_day: 'monday',
        original_view: 'order_items',
        dimension_group: null,
        error: null,
        field_group_variant: 'Average Sale Price',
        measure: true,
        parameter: false,
        primary_key: false,
        project_name: 'looker_partner_demo',
        scope: 'order_items',
        suggest_dimension: 'order_items.average_sale_price',
        suggest_explore: 'order_items',
        suggestable: false,
        is_fiscal: false,
        is_timeframe: false,
        can_time_filter: false,
        time_interval: null,
        lookml_link:
          '/projects/looker_partner_demo/files/views%2F01_order_items.view.lkml?line=356',
        permanent: null,
        source_file: 'views/01_order_items.view.lkml',
        source_file_path: 'looker_partner_demo/views/01_order_items.view.lkml',
        sql: '${sale_price} ',
        sql_case: null,
        filters: null,
        times_used: 0,
        sorted: {
          desc: true,
          sort_index: 1,
        },
      },
      {
        align: 'right',
        can_filter: true,
        category: 'measure',
        default_filter_value: null,
        description: '',
        enumerations: null,
        field_group_label: null,
        fill_style: null,
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: true,
        label: 'Order Items Count',
        label_from_parameter: null,
        label_short: 'Count',
        map_layer: null,
        name: 'order_items.count',
        strict_value_format: false,
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: [],
        type: 'count',
        user_attribute_filter_types: ['number', 'advanced_filter_number'],
        value_format: null,
        view: 'order_items',
        view_label: 'Order Items',
        dynamic: false,
        week_start_day: 'monday',
        original_view: 'order_items',
        dimension_group: null,
        error: null,
        field_group_variant: 'Count',
        measure: true,
        parameter: false,
        primary_key: false,
        project_name: 'looker_partner_demo',
        scope: 'order_items',
        suggest_dimension: 'order_items.count',
        suggest_explore: 'order_items',
        suggestable: false,
        is_fiscal: false,
        is_timeframe: false,
        can_time_filter: false,
        time_interval: null,
        lookml_link:
          '/projects/looker_partner_demo/files/views%2F01_order_items.view.lkml?line=57',
        permanent: null,
        source_file: 'views/01_order_items.view.lkml',
        source_file_path: 'looker_partner_demo/views/01_order_items.view.lkml',
        sql: null,
        sql_case: null,
        filters: null,
        times_used: 0,
      },
      {
        align: 'right',
        can_filter: true,
        category: 'measure',
        default_filter_value: null,
        description: '',
        enumerations: null,
        field_group_label: null,
        fill_style: null,
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: true,
        label: 'Order Items Total Sale Price',
        label_from_parameter: null,
        label_short: 'Total Sale Price',
        map_layer: null,
        name: 'order_items.total_sale_price',
        strict_value_format: false,
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: [],
        type: 'sum',
        user_attribute_filter_types: ['number', 'advanced_filter_number'],
        value_format: '$#,##0.00',
        view: 'order_items',
        view_label: 'Order Items',
        dynamic: false,
        week_start_day: 'monday',
        original_view: 'order_items',
        dimension_group: null,
        error: null,
        field_group_variant: 'Total Sale Price',
        measure: true,
        parameter: false,
        primary_key: false,
        project_name: 'looker_partner_demo',
        scope: 'order_items',
        suggest_dimension: 'order_items.total_sale_price',
        suggest_explore: 'order_items',
        suggestable: false,
        is_fiscal: false,
        is_timeframe: false,
        can_time_filter: false,
        time_interval: null,
        lookml_link:
          '/projects/looker_partner_demo/files/views%2F01_order_items.view.lkml?line=338',
        permanent: null,
        source_file: 'views/01_order_items.view.lkml',
        source_file_path: 'looker_partner_demo/views/01_order_items.view.lkml',
        sql: '${sale_price} ',
        sql_case: null,
        filters: null,
        times_used: 0,
      },
    ],
    dimensions: [
      {
        align: 'left',
        can_filter: true,
        category: 'dimension',
        default_filter_value: null,
        description: 'Users/Customers gender',
        enumerations: null,
        field_group_label: null,
        fill_style: null,
        fiscal_month_offset: 0,
        has_allowed_values: false,
        hidden: false,
        is_filter: false,
        is_numeric: false,
        label: 'Users Gender',
        label_from_parameter: null,
        label_short: 'Gender',
        map_layer: null,
        name: 'users.gender',
        strict_value_format: false,
        requires_refresh_on_sort: false,
        sortable: true,
        suggestions: null,
        tags: ['Users/Customers gender'],
        type: 'string',
        user_attribute_filter_types: ['string', 'advanced_filter_string'],
        value_format: null,
        view: 'users',
        view_label: 'Users',
        dynamic: false,
        week_start_day: 'monday',
        original_view: 'users',
        dimension_group: null,
        error: null,
        field_group_variant: 'Gender',
        measure: false,
        parameter: false,
        primary_key: false,
        project_name: 'looker_partner_demo',
        scope: 'users',
        suggest_dimension: 'users.gender',
        suggest_explore: 'order_items',
        suggestable: true,
        is_fiscal: false,
        is_timeframe: false,
        can_time_filter: false,
        time_interval: null,
        lookml_link:
          '/projects/looker_partner_demo/files/views%2F02_users.view.lkml?line=82',
        permanent: null,
        source_file: 'views/02_users.view.lkml',
        source_file_path: 'looker_partner_demo/views/02_users.view.lkml',
        sql: '${TABLE}.gender ',
        sql_case: null,
        filters: null,
        times_used: 0,
      },
    ],
    table_calculations: [],
    pivots: [],
  },
};

export const data = [
  {
    'users.gender': {
      value: 'Male',
    },
    'order_items.average_sale_price': {
      value: 47.92918670638953,
      rendered: '$47.93',
      links: [
        {
          label: 'Show All $47.93',
          label_prefix: 'Show All',
          label_value: '$47.93',
          url: '/explore/thelook_partner/order_items?fields=order_items.order_id,order_items.status,order_items.created_date,order_items.sale_price,products.brand,products.item_name,users.name,users.email&f[users.gender]=Male&f[users.state]=&f[users.city]=&f[users.traffic_source]=&f[order_items.created_date]=90+days&f[distribution_centers.location]=&f[users.country]=&query_timezone=Europe%2FMadrid&limit=500',
          type: 'measure_default',
        },
      ],
    },
    'order_items.count': {
      value: 13768,
      rendered: '13,768',
      links: [
        {
          label: 'Show All 13,768',
          label_prefix: 'Show All',
          label_value: '13,768',
          url: '/explore/thelook_partner/order_items?fields=order_items.order_id,order_items.status,order_items.created_date,order_items.sale_price,products.brand,products.item_name,users.name,users.email&f[users.gender]=Male&f[users.state]=&f[users.city]=&f[users.traffic_source]=&f[order_items.created_date]=90+days&f[distribution_centers.location]=&f[users.country]=&query_timezone=Europe%2FMadrid&limit=500',
          type: 'measure_default',
        },
      ],
    },
    'order_items.total_sale_price': {
      value: 659889.0425735712,
      rendered: '$659,889.04',
      links: [
        {
          label: 'Show All $659,889.04',
          label_prefix: 'Show All',
          label_value: '$659,889.04',
          url: '/explore/thelook_partner/order_items?fields=order_items.total_sale_price,products.category&f[users.gender]=Male&f[users.state]=&f[users.city]=&f[users.traffic_source]=&f[order_items.created_date]=90+days&f[distribution_centers.location]=&f[users.country]=&query_timezone=Europe%2FMadrid&limit=500',
          type: 'measure_default',
        },
      ],
    },
  },
  {
    'users.gender': {
      value: 'Female',
    },
    'order_items.average_sale_price': {
      value: 44.27421166761676,
      rendered: '$44.27',
      links: [
        {
          label: 'Show All $44.27',
          label_prefix: 'Show All',
          label_value: '$44.27',
          url: '/explore/thelook_partner/order_items?fields=order_items.order_id,order_items.status,order_items.created_date,order_items.sale_price,products.brand,products.item_name,users.name,users.email&f[users.gender]=Female&f[users.state]=&f[users.city]=&f[users.traffic_source]=&f[order_items.created_date]=90+days&f[distribution_centers.location]=&f[users.country]=&query_timezone=Europe%2FMadrid&limit=500',
          type: 'measure_default',
        },
      ],
    },
    'order_items.count': {
      value: 17343,
      rendered: '17,343',
      links: [
        {
          label: 'Show All 17,343',
          label_prefix: 'Show All',
          label_value: '17,343',
          url: '/explore/thelook_partner/order_items?fields=order_items.order_id,order_items.status,order_items.created_date,order_items.sale_price,products.brand,products.item_name,users.name,users.email&f[users.gender]=Female&f[users.state]=&f[users.city]=&f[users.traffic_source]=&f[order_items.created_date]=90+days&f[distribution_centers.location]=&f[users.country]=&query_timezone=Europe%2FMadrid&limit=500',
          type: 'measure_default',
        },
      ],
    },
    'order_items.total_sale_price': {
      value: 767847.652951479,
      rendered: '$767,847.65',
      links: [
        {
          label: 'Show All $767,847.65',
          label_prefix: 'Show All',
          label_value: '$767,847.65',
          url: '/explore/thelook_partner/order_items?fields=order_items.total_sale_price,products.category&f[users.gender]=Female&f[users.state]=&f[users.city]=&f[users.traffic_source]=&f[order_items.created_date]=90+days&f[distribution_centers.location]=&f[users.country]=&query_timezone=Europe%2FMadrid&limit=500',
          type: 'measure_default',
        },
      ],
    },
  },
];
